//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmeri
    {
        public Farmeri()
        {
            this.Aktivnosti = new HashSet<Aktivnosti>();
        }
    
        public int ID { get; set; }
        public string OIB { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
    
        public virtual ICollection<Aktivnosti> Aktivnosti { get; set; }
    }
}
