<?xml version="1.0" encoding="utf-8"?><Database Name="FarmeronBaza" Class="ActionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=IVAN-PC\SQLEXPRESS;Initial Catalog=FarmeronBaza;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FarmeronBazaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Aktivnosti" Member="Aktivnostis">
    <Type Name="Aktivnosti">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idFarmera" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stanje" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>