//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileData
    {
        public int ID { get; set; }
        public string SourceFile { get; set; }
        public string ExpectedFile { get; set; }
        public Nullable<int> NodeID { get; set; }
        public string NodeValue { get; set; }
        public string Xpath { get; set; }
    
        public virtual Node Node { get; set; }
    }
}
